/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  KittyG
 * Created: 2016-5-8
 */
CREATE DATABASE `student` DEFAULT CHARACTER SET utf8;

CREATE TABLE `student`.`login` (
  `USERID` VARCHAR(10) NOT NULL,
  `MD5PASSWORD` VARCHAR(32) NOT NULL,
  `USERNAME` VARCHAR(45) NULL DEFAULT '未命名',
  `IDENTITY` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`USERID`));


CREATE TABLE `student`.`major` (
  `MAJORCODE` VARCHAR(4) NOT NULL,
  `MAJORNAME` VARCHAR(50) NOT NULL,
  `ACADEMYCODE` VARCHAR(2) NOT NULL,
  `ACADEMYNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`MAJORCODE`));


CREATE TABLE `student`.`student` (
  `USERID` VARCHAR(10) NOT NULL,
  `USERNAME` VARCHAR(45) NULL,
  `IDENTITY` INT NOT NULL DEFAULT 0,
  `GENDER` INT NOT NULL DEFAULT 0,
  `CREATETIME` DATETIME NOT NULL DEFAULT now(),
  `GRADE` INT NOT NULL,
  `MAJORCODE` VARCHAR(45) NOT NULL,
  `CLASSNO` INT NOT NULL,
  `INTENDEDTIME` DATETIME NOT NULL,
  INDEX `USERID_idx` (`USERID` ASC),
  INDEX `MAJORCODE_idx` (`MAJORCODE` ASC),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MAJORCODE`
    FOREIGN KEY (`MAJORCODE`)
    REFERENCES `student`.`major` (`MAJORCODE`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


CREATE TABLE `administrator` (
  `USERID` varchar(10) NOT NULL,
  `USERNAME` varchar(45) DEFAULT NULL,
  `IDENTITY` int(11) NOT NULL DEFAULT '0',
  `GENDER` int(11) NOT NULL DEFAULT '0',
  `CREATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MANAGELEVEL` int(11) NOT NULL DEFAULT '0',
  `TELEPHONE` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(80) DEFAULT NULL,
  KEY `USERID_idx` (`USERID`),
  CONSTRAINT `ADMINISTRATOR_USERID` FOREIGN KEY (`USERID`) REFERENCES `login` (`USERID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

