/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  KittyG
 * Created: 2016-5-8
 */
CREATE DATABASE `student` DEFAULT CHARACTER SET utf8;

CREATE TABLE `student`.`login` (
  `USERID` VARCHAR(10) NOT NULL,
  `MD5PASSWORD` VARCHAR(32) NOT NULL,
  `USERNAME` VARCHAR(45) NULL DEFAULT '未命名',
  `IDENTITY` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`USERID`));


CREATE TABLE `student`.`major` (
  `MAJORCODE` VARCHAR(4) NOT NULL,
  `MAJORNAME` VARCHAR(50) NOT NULL,
  `ACADEMYCODE` VARCHAR(2) NOT NULL,
  `ACADEMYNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`MAJORCODE`));


CREATE TABLE `student`.`student` (
  `USERID` VARCHAR(10) NOT NULL,
  `USERNAME` VARCHAR(45) NULL,
  `IDENTITY` INT NOT NULL DEFAULT 0,
  `GENDER` INT NOT NULL DEFAULT 0,
  `CREATETIME` DATETIME NOT NULL DEFAULT now(),
  `GRADE` INT NOT NULL,
  `MAJORCODE` VARCHAR(45) NOT NULL,
  `CLASSNO` INT NOT NULL,
  `INTENDEDTIME` DATETIME NOT NULL,
  INDEX `USERID_idx` (`USERID` ASC),
  INDEX `MAJORCODE_idx` (`MAJORCODE` ASC),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MAJORCODE`
    FOREIGN KEY (`MAJORCODE`)
    REFERENCES `student`.`major` (`MAJORCODE`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


CREATE TABLE `administrator` (
  `USERID` varchar(10) NOT NULL,
  `USERNAME` varchar(45) DEFAULT NULL,
  `IDENTITY` int(11) NOT NULL DEFAULT '0',
  `GENDER` int(11) NOT NULL DEFAULT '0',
  `CREATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MANAGELEVEL` int(11) NOT NULL DEFAULT '0',
  `TELEPHONE` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(80) DEFAULT NULL,
  KEY `USERID_idx` (`USERID`),
  CONSTRAINT `ADMINISTRATOR_USERID` FOREIGN KEY (`USERID`) REFERENCES `login` (`USERID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `student`.`managingdepartment` (
  `ADMINISTRATORID` VARCHAR(10) NOT NULL,
  `DEPARTMENTCODE` VARCHAR(4) NOT NULL,
  `DEPARTMENTLEVEL` INT NOT NULL,
  INDEX `managingdepartment_idx` (`ADMINISTRATORID` ASC),
  CONSTRAINT `managingdepartment`
    FOREIGN KEY (`ADMINISTRATORID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE `student`.`needystudent` (
  `USERID` VARCHAR(10) NOT NULL,
  `IDCARDNUMBER` VARCHAR(20) NULL,
  `TELEPHONE` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(80) NULL,
  `ADDRESS` VARCHAR(100) NULL,
  `ORIGINCODE` VARCHAR(4) NULL,
  `DORMROOM` VARCHAR(10) NULL,
  `PERSONSPECIALITY` VARCHAR(200) NULL,
  `RECEIVEDAWARD` VARCHAR(300) NULL,
  `POVERTYLEVEL` INT NULL,
  `POVERTYREASON` VARCHAR(300) NULL,
  `APPLICATIONDATE` DATETIME NOT NULL,
  `VALIDATEDDATE` DATETIME NULL,
  INDEX `NEEDYSTUDENT_USERID_idx` (`USERID` ASC),
  CONSTRAINT `NEEDYSTUDENT_USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE `student`.`activity` (
  `NOTICEID` VARCHAR(20) NOT NULL,
  `NOTICETITLE` VARCHAR(30) NULL,
  `NOTICECONTENT` VARCHAR(1000) NULL,
  `ADMINISTRATORID` VARCHAR(10) NOT NULL,
  `NOTICETYPE` INT NOT NULL DEFAULT 0,
  `NOTICESTATUS` INT NOT NULL DEFAULT 0,
  `IMAGECOUNT` INT NULL DEFAULT 0,
  `CREATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTIVITYTYPE` INT NOT NULL DEFAULT 0,
  `IDENTITYLEVEL` INT NOT NULL,
  `LIMITPEOPLENUMBER` INT NULL,
  PRIMARY KEY (`NOTICEID`),
  INDEX `ACTIVITY_ADMINISTRATORID_idx` (`ADMINISTRATORID` ASC),
  CONSTRAINT `ACTIVITY_ADMINISTRATORID`
    FOREIGN KEY (`ADMINISTRATORID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

CREATE TABLE `student`.`news` (
  `NOTICEID` VARCHAR(20) NOT NULL,
  `NOTICETITLE` VARCHAR(30) NULL DEFAULT NULL,
  `NOTICECONTENT` VARCHAR(2000) NULL DEFAULT NULL,
  `ADMINISTRATORID` VARCHAR(10) NOT NULL,
  `NOTICETYPE` INT NOT NULL DEFAULT 0,
  `NOTICESTATUS` INT NOT NULL DEFAULT 0,
  `IMAGECOUNT` INT NULL DEFAULT 0,
  `CREATETIME` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`NOTICEID`),
  INDEX `NEWS_ADMINISTRATORID_idx` (`ADMINISTRATORID` ASC),
  CONSTRAINT `NEWS_ADMINISTRATORID`
    FOREIGN KEY (`ADMINISTRATORID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

CREATE TABLE `student`.`comment` (
  `COMMENTID` VARCHAR(20) NOT NULL,
  `ACTIVITYID` VARCHAR(20) NOT NULL,
  `USERID` VARCHAR(10) NOT NULL,
  `COMMENTCONTENT` VARCHAR(200) NULL,
  `COMMENTTYPE` INT NOT NULL DEFAULT 0,
  `REPLYCOMMENTID` VARCHAR(20) NULL,
  `COMMENTSTATUS` INT NOT NULL DEFAULT 0,
  `ANONYMOUS` BIT NULL DEFAULT 0,
  `CREATETIME` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`COMMENTID`),
  INDEX `COMMENT_ACTIVITYID_idx` (`ACTIVITYID` ASC),
  INDEX `COMMENT_USERID_idx` (`USERID` ASC),
  CONSTRAINT `COMMENT_ACTIVITYID`
    FOREIGN KEY (`ACTIVITYID`)
    REFERENCES `student`.`activity` (`NOTICEID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COMMENT_USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

CREATE TABLE `student`.`activityattendee` (
  `ACTIVITYID` VARCHAR(20) NOT NULL,
  `USERID` VARCHAR(10) NOT NULL,
  `SIGNUPSTATUS` INT NOT NULL DEFAULT 0,
  `CREATETIME` DATETIME NOT NULL DEFAULT now(),
  INDEX `ACTIVITYATTENDEE_ACTIVITYID_idx` (`ACTIVITYID` ASC),
  INDEX `ACTIVITYATTENDEE_USERID_idx` (`USERID` ASC),
  CONSTRAINT `ACTIVITYATTENDEE_ACTIVITYID`
    FOREIGN KEY (`ACTIVITYID`)
    REFERENCES `student`.`activity` (`NOTICEID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ACTIVITYATTENDEE_USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `student`.`login` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

CREATE TABLE `student`.`image` (
  `IMAGEID` VARCHAR(20) NOT NULL,
  `IMAGENAME` VARCHAR(30) NULL DEFAULT 'no title',
  `NOTICEID` VARCHAR(20) NOT NULL,
  `NOTICETYPE` INT NOT NULL,
  `RELATIVEPATH` VARCHAR(300) NOT NULL,
  `CREATETIME` DATETIME NOT NULL,
  PRIMARY KEY (`IMAGEID`),
  INDEX `ACTIVITY_NOTICEID_idx` (`NOTICEID` ASC),
  CONSTRAINT `ACTIVITY_NOTICEID`
    FOREIGN KEY (`NOTICEID`)
    REFERENCES `student`.`activity` (`NOTICEID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `NEWS_NOTICEID`
    FOREIGN KEY (`NOTICEID`)
    REFERENCES `student`.`news` (`NOTICEID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
